require 'sunlight/influence'

class Sunlight::Influence::FederalContracts
  attr_reader :contractingofficeid, :srdvobflag, :reasonnotcompeted, :seatransportation, :hubzoneflag, :contractbundling,
              :hbcuflag, :annualrevenue, :majorprogramcode, :firm8aflag, :smallbusinesscompetitivenessdemonstrationprogram,
              :tribalgovernmentflag, :apaobflag, :emergingsmallbusinessflag, :naobflag, :idvpiid, :locationcode, :isserviceprovider,
              :extentcompeted, :hospitalflag, :effectivedate, :reasonformodification , :agency_name, :receivesgrants,
              :purchasecardaspaymentmethod, :numberofactions, :phoneno, :idvmodificationnumber, :localareasetaside,
              :agencyid, :countryoforigin, :educationalinstitutionflag, :contractactiontype, :multiyearcontract,
              :saaobflag, :consolidatedcontract, :subcontractplan, :manufacturingorganizationtype, :federalgovernmentflag,
              :rec_flag, :typeofsetaside, :fundingrequestingofficeid, :competitiveprocedures, :streetaddress, :costaccountingstandardsclause,
              :transaction_status, :mod_agency, :nonprofitorganizationflag, :vendorenabled, :ultimatecompletiondate, :vendorlegalorganizationname,
              :gfe_gfp, :programacronym, :research, :state, :statutoryexceptiontofairopportunity, :recoveredmaterialclauses,
              :contingencyhumanitarianpeacekeepingoperation, :haobflag, :descriptionofcontractrequirement, :receivescontracts,
              :vendorlocationdisableflag, :vendoralternatesitecode, :maj_fund_agency_cat, :placeofperformancezipcode, :obligatedamount,
              :davisbaconact, :parentdunsnumber, :costorpricingdata, :multipleorsingleawardidc, :minorityinstitutionflag, :contractfinancing,
              :principalnaicscode, :fundingrequestingagencyid, :lastdatetoorder, :stategovernmentflag, :claimantprogramcode, :walshhealyact,
              :commercialitemtestprogram, :mod_parent, :baseandalloptionsvalue, :placeofmanufacture, :fiscal_year, :vendoralternatename,
              :minorityownedbusinessflag, :priceevaluationpercentdifference, :city, :numberofoffersreceived, :commercialitemacquisitionprocedures,
              :veteranownedflag, :evaluatedpreference, :informationtechnologycommercialitemcategory, :useofepadesignatedproducts, :aiobflag,
              :maj_agency_cat, :psc_cat, :transactionnumber, :pop_cd, :baseandexercisedoptionsvalue, :modnumber, :idvagencyid, :organizationaltype,
              :statecode, :solicitationprocedures, :congressionaldistrict, :vendorname, :productorservicecode, :receivescontractsandgrants,
              :currentcompletiondate, :performancebasedservicecontract, :piid, :progsourcesubacct, :divisionname, :baobflag, :contracting_agency_name,
              :womenownedflag, :vendor_state_code, :fedbizopps, :vendordoingasbusinessname , :ccrexception , :divisionnumberorofficecode ,
              :unique_transaction_id, :localgovernmentflag, :servicecontractact, :systemequipmentcode, :solicitationid, :sdbflag, :id,
              :streetaddress3, :progsourceaccount, :zipcode, :progsourceagency, :interagencycontractingauthority, :contractingofficeagencyid,
              :account_title, :vendorsitecode, :numberofemployees, :streetaddress2, :vendorcountrycode, :fundedbyforeignentity, :otherstatutoryauthority,
              :dunsnumber, :placeofperformancecongressionaldistrict, :placeofperformancecountrycode, :vendor_cd, :lettercontract, :registrationdate,
              :shelteredworkshopflag, :contractingofficerbusinesssizedetermination, :pop_state_code, :typeofcontractpricing, :faxno,
              :signeddate, :nationalinterestactioncode, :a76action, :typeofidc, :renewaldate, :clingercohenact, :requesting_agency_name


  def initialize(attrs)
    self.contractingofficeid                              = attrs[:contractingofficeid]
    self.srdvobflag                                       = attrs[:srdvobflag]
    self.reasonnotcompeted                                = attrs[:reasonnotcompeted]
    self.seatransportation                                = attrs[:seatransportation]
    self.hubzoneflag                                      = attrs[:hubzoneflag]
    self.contractbundling                                 = attrs[:contractbundling]
    self.hbcuflag                                         = attrs[:hbcuflag]
    self.annualrevenue                                    = attrs[:annualrevenue]
    self.majorprogramcode                                 = attrs[:majorprogramcode]
    self.firm8aflag                                       = attrs[:firm8aflag]
    self.smallbusinesscompetitivenessdemonstrationprogram = attrs[:smallbusinesscompetitivenessdemonstrationprogram]
    self.tribalgovernmentflag                             = attrs[:tribalgovernmentflag]
    self.apaobflag                                        = attrs[:apaobflag]
    self.emergingsmallbusinessflag                        = attrs[:emergingsmallbusinessflag]
    self.naobflag                                         = attrs[:naobflag]
    self.idvpiid                                          = attrs[:idvpiid]
    self.locationcode                                     = attrs[:locationcode]
    self.isserviceprovider                                = attrs[:isserviceprovider]
    self.extentcompeted                                   = attrs[:extentcompeted]
    self.hospitalflag                                     = attrs[:hospitalflag]
    self.effectivedate                                    = attrs[:effectivedate]
    self.reasonformodification                            = attrs[:reasonformodification]
    self.agency_name                                      = attrs[:agency_name]
    self.receivesgrants                                   = attrs[:receivesgrants]
    self.purchasecardaspaymentmethod                      = attrs[:purchasecardaspaymentmethod]
    self.numberofactions                                  = attrs[:numberofactions]
    self.phoneno                                          = attrs[:phoneno]
    self.idvmodificationnumber                            = attrs[:idvmodificationnumber]
    self.localareasetaside                                = attrs[:localareasetaside]
    self.agencyid                                         = attrs[:agencyid]
    self.countryoforigin                                  = attrs[:countryoforigin]
    self.educationalinstitutionflag                       = attrs[:educationalinstitutionflag]
    self.contractactiontype                               = attrs[:contractactiontype]
    self.multiyearcontract                                = attrs[:multiyearcontract]
    self.saaobflag                                        = attrs[:saaobflag]
    self.consolidatedcontract                             = attrs[:consolidatedcontract]
    self.subcontractplan                                  = attrs[:subcontractplan]
    self.manufacturingorganizationtype                    = attrs[:manufacturingorganizationtype]
    self.federalgovernmentflag                            = attrs[:federalgovernmentflag]
    self.rec_flag                                         = attrs[:rec_flag]
    self.typeofsetaside                                   = attrs[:typeofsetaside]
    self.fundingrequestingofficeid                        = attrs[:fundingrequestingofficeid]
    self.competitiveprocedures                            = attrs[:competitiveprocedures]
    self.streetaddress                                    = attrs[:streetaddress]
    self.costaccountingstandardsclause                    = attrs[:costaccountingstandardsclause]
    self.transaction_status                               = attrs[:transaction_status]
    self.mod_agency                                       = attrs[:mod_agency]
    self.nonprofitorganizationflag                        = attrs[:nonprofitorganizationflag]
    self.vendorenabled                                    = attrs[:vendorenabled]
    self.ultimatecompletiondate                           = attrs[:ultimatecompletiondate]
    self.vendorlegalorganizationname                      = attrs[:vendorlegalorganizationname]
    self.gfe_gfp                                          = attrs[:gfe_gfp]
    self.programacronym                                   = attrs[:programacronym]
    self.research                                         = attrs[:research]
    self.state                                            = attrs[:state]
    self.statutoryexceptiontofairopportunity              = attrs[:statutoryexceptiontofairopportunity]
    self.recoveredmaterialclauses                         = attrs[:recoveredmaterialclauses]
    self.contingencyhumanitarianpeacekeepingoperation     = attrs[:contingencyhumanitarianpeacekeepingoperation]
    self.haobflag                                         = attrs[:haobflag]
    self.descriptionofcontractrequirement                 = attrs[:descriptionofcontractrequirement]
    self.receivescontracts                                = attrs[:receivescontracts]
    self.vendorlocationdisableflag                        = attrs[:vendorlocationdisableflag]
    self.vendoralternatesitecode                          = attrs[:vendoralternatesitecode]
    self.maj_fund_agency_cat                              = attrs[:maj_fund_agency_cat]
    self.placeofperformancezipcode                        = attrs[:placeofperformancezipcode]
    self.obligatedamount                                  = attrs[:obligatedamount]
    self.davisbaconact                                    = attrs[:davisbaconact]
    self.parentdunsnumber                                 = attrs[:parentdunsnumber]
    self.costorpricingdata                                = attrs[:costorpricingdata]
    self.multipleorsingleawardidc                         = attrs[:multipleorsingleawardidc]
    self.minorityinstitutionflag                          = attrs[:minorityinstitutionflag]
    self.contractfinancing                                = attrs[:contractfinancing]
    self.principalnaicscode                               = attrs[:principalnaicscode]
    self.fundingrequestingagencyid                        = attrs[:fundingrequestingagencyid]
    self.lastdatetoorder                                  = attrs[:lastdatetoorder]
    self.stategovernmentflag                              = attrs[:stategovernmentflag]
    self.claimantprogramcode                              = attrs[:claimantprogramcode]
    self.walshhealyact                                    = attrs[:walshhealyact]
    self.commercialitemtestprogram                        = attrs[:commercialitemtestprogram]
    self.mod_parent                                       = attrs[:mod_parent]
    self.baseandalloptionsvalue                           = attrs[:baseandalloptionsvalue]
    self.placeofmanufacture                               = attrs[:placeofmanufacture]
    self.fiscal_year                                      = attrs[:fiscal_year]
    self.vendoralternatename                              = attrs[:vendoralternatename]
    self.minorityownedbusinessflag                        = attrs[:minorityownedbusinessflag]
    self.priceevaluationpercentdifference                 = attrs[:priceevaluationpercentdifference]
    self.city                                             = attrs[:city]
    self.numberofoffersreceived                           = attrs[:numberofoffersreceived]
    self.commercialitemacquisitionprocedures              = attrs[:commercialitemacquisitionprocedures]
    self.veteranownedflag                                 = attrs[:veteranownedflag]
    self.evaluatedpreference                              = attrs[:evaluatedpreference]
    self.informationtechnologycommercialitemcategory      = attrs[:informationtechnologycommercialitemcategory]
    self.useofepadesignatedproducts                       = attrs[:useofepadesignatedproducts]
    self.aiobflag                                         = attrs[:aiobflag]
    self.maj_agency_cat                                   = attrs[:maj_agency_cat]
    self.psc_cat                                          = attrs[:psc_cat]
    self.transactionnumber                                = attrs[:transactionnumber]
    self.pop_cd                                           = attrs[:pop_cd]
    self.baseandexercisedoptionsvalue                     = attrs[:baseandexercisedoptionsvalue]
    self.modnumber                                        = attrs[:modnumber]
    self.idvagencyid                                      = attrs[:idvagencyid]
    self.organizationaltype                               = attrs[:organizationaltype]
    self.statecode                                        = attrs[:statecode]
    self.solicitationprocedures                           = attrs[:solicitationprocedures]
    self.congressionaldistrict                            = attrs[:congressionaldistrict]
    self.vendorname                                       = attrs[:vendorname]
    self.productorservicecode                             = attrs[:productorservicecode]
    self.receivescontractsandgrants                       = attrs[:receivescontractsandgrants]
    self.currentcompletiondate                            = attrs[:currentcompletiondate]
    self.performancebasedservicecontract                  = attrs[:performancebasedservicecontract]
    self.piid                                             = attrs[:piid]
    self.progsourcesubacct                                = attrs[:progsourcesubacct]
    self.divisionname                                     = attrs[:divisionname]
    self.baobflag                                         = attrs[:baobflag]
    self.contracting_agency_name                          = attrs[:contracting_agency_name]
    self.womenownedflag                                   = attrs[:womenownedflag]
    self.vendor_state_code                                = attrs[:vendor_state_code]
    self.fedbizopps                                       = attrs[:fedbizopps]
    self.vendordoingasbusinessname                        = attrs[:vendordoingasbusinessname]
    self.ccrexception                                     = attrs[:ccrexception ]
    self.divisionnumberorofficecode                       = attrs[:divisionnumberorofficecode ]
    self.unique_transaction_id                            = attrs[:unique_transaction_id]
    self.localgovernmentflag                              = attrs[:localgovernmentflag]
    self.servicecontractact                               = attrs[:servicecontractact]
    self.systemequipmentcode                              = attrs[:systemequipmentcode]
    self.solicitationid                                   = attrs[:solicitationid]
    self.sdbflag                                          = attrs[:sdbflag]
    self.id                                               = attrs[:id]
    self.streetaddress3                                   = attrs[:streetaddress3]
    self.progsourceaccount                                = attrs[:progsourceaccount]
    self.zipcode                                          = attrs[:zipcode]
    self.progsourceagency                                 = attrs[:progsourceagency]
    self.interagencycontractingauthority                  = attrs[:interagencycontractingauthority]
    self.contractingofficeagencyid                        = attrs[:contractingofficeagencyid]
    self.account_title                                    = attrs[:account_title]
    self.vendorsitecode                                   = attrs[:vendorsitecode]
    self.numberofemployees                                = attrs[:numberofemployees]
    self.streetaddress2                                   = attrs[:streetaddress2]
    self.vendorcountrycode                                = attrs[:vendorcountrycode]
    self.fundedbyforeignentity                            = attrs[:fundedbyforeignentity]
    self.otherstatutoryauthority                          = attrs[:otherstatutoryauthority]
    self.dunsnumber                                       = attrs[:dunsnumber]
    self.placeofperformancecongressionaldistrict          = attrs[:placeofperformancecongressionaldistrict]
    self.placeofperformancecountrycode                    = attrs[:placeofperformancecountrycode]
    self.vendor_cd                                        = attrs[:vendor_cd]
    self.lettercontract                                   = attrs[:lettercontract]
    self.registrationdate                                 = attrs[:registrationdate]
    self.shelteredworkshopflag                            = attrs[:shelteredworkshopflag]
    self.contractingofficerbusinesssizedetermination      = attrs[:contractingofficerbusinesssizedetermination]
    self.pop_state_code                                   = attrs[:pop_state_code]
    self.typeofcontractpricing                            = attrs[:typeofcontractpricing]
    self.faxno                                            = attrs[:faxno]
    self.signeddate                                       = attrs[:signeddate]
    self.nationalinterestactioncode                       = attrs[:nationalinterestactioncode]
    self.a76action                                        = attrs[:a76action]
    self.typeofidc                                        = attrs[:typeofidc]
    self.renewaldate                                      = attrs[:renewaldate]
    self.clingercohenact                                  = attrs[:clingercohenact]
    self.requesting_agency_name                           = attrs[:requesting_agency_name]
  end

end
